global:
  scrape_interval: 15s # Prometheus polls /metrics on each service every 15 seconds.

scrape_configs:
  - job_name: ingestion-service
    static_configs:
      - targets: ["ingestion-service:8000"]

  - job_name: query-service
    static_configs:
      - targets: ["query-service:8001"]
